### ISSUE TITLE
read with -i option doesn't work on mac bash?

### ISSUE THREAD

**Issue by IJEMIN** [3d-group/unity-package-template#15]
When I run RUNME.sh on my mac machine terminal, it can not handle read commands with i option.

```read -e -p "Unity version: " -i "2019.4" UNITY_VERSION```

it prints...
>> bash: read: -i: invalid option

I though mac may change script interpreter with zsh because zsh is default mac shell.
So I ran script on bash instance on mac terminal. But still doesn't work .

Any idea?

**Comment by antja0** [comment]
Thank you for pointing this out. This should be fixed now.
